[Version]
Class=IExpress
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=D:\LAB\CODING\baroTool\Setup\BaroTool.exe
FriendlyName=BaroTool
AppLaunched=cmd.exe /c launcher.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="launcher.bat"
FILE1="7z.exe"
FILE2="7z.dll"
FILE3="Setup.7z"
[SourceFiles]
SourceFiles0=D:\LAB\CODING\baroTool\Setup\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
